name: build vue
on: 
  push:
    branches:
      - master
jobs:
  build-vue:
    runs-on: ubuntu-latest
    name: build vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'chaoowen'
        reponame: 'self-introduction'
        token: ${{ secrets.GITHUB_TOKEN }}